spring:
  datasource:
    url: jdbc:h2:/Users/silencer/IdeaProjects/silencer-examples/delete-and-insert/src/main/resources/db/default;AUTO_SERVER=TRUE
    username: test
    password: asdf1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
#       show-sql: true
