spring:
  datasource:
    url: jdbc:h2:/Users/silencer/IdeaProjects/silencer-examples/one-to-many/src/main/resources/db/default;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    username: test
    password: asdf1234

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true